apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-app
spec:  
  replicas: 2
  selector:  
    matchLabels:
      app: api
  template:
    metadata: 
      labels:
        app: api
    spec:
      containers: 
        - name: api-app
          image: kasiapetka/mgr-prod:api
          imagePullPolicy: Always
          resources:
           limits:
            memory: "128Mi"
            cpu: "1"

