apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template: 
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react-container 
          image: kasiapetka/mgr-prod:react
          imagePullPolicy: Always
          resources:
           limits:
            memory: "128Mi"
            cpu: "1"