name: Build docker images and push them to a registry
on:
 push:
   branches:
     - 'master'
     - 'main'

 workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push react app
        uses: docker/build-push-action@v3
        with:
          context: ./rea-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mgr-prod:react
      -
        name: Build and push nodejs app
        uses: docker/build-push-action@v3
        with:
          context: ./opti-frame-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mgr-prod:api